# Server settings  
server:  
    port: 8090
    address: 127.0.0.1
    
# SPRING PROFILES  
spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
    mvc:
        view.prefix: /WEB-INF/jsp/
        view.suffix: .jsp

    # DATASOURCE  
    datasource: 
        driverClass: com.mysql.jdbc.Driver  
        url: jdbc:mysql://119.29.112.212:3306/test?useUnicode=true&characterEncoding=utf-8  
        username: root  
        password: redhat
    redis:

        #database: 0 
        host: 127.0.0.1 # server host  
        #password: # server password  
        port: 6379 # connection port  
mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
logging:
  config: classpath:logback-spring.xml
  path: F:\\
  #file: F:\\springboot.log
  level.org.springframework.web: INFO
